<?php

$dictionary['PPT_SPQ'] = array(
    'table' => 'ppt_spq',
    'audited' => false,
    'inline_edit' => true,
    'duplicate_merge' => 'disabled',
    'fields' => array(
        'number' => array(
            'name' => 'number',
            'vname' => 'LBL_NUMBER',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'air_waybill' => array(
            'name' => 'air_waybill',
            'vname' => 'LBL_AIR_WAYBILL',
            'type' => 'long',
            'dbType' => 'bigint',
            'default' => 0,
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'origin' => array(
            'name' => 'origin',
            'vname' => 'LBL_ORIGIN',
            'type' => 'enum',
            'options' => 'ppt-airports-dom',
            'len' => 50,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'dest' => array(
            'name' => 'dest',
            'vname' => 'LBL_DEST',
            'type' => 'enum',
            'options' => 'ppt-airports-dom',
            'len' => 50,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'service' => array(
            'name' => 'service',
            'vname' => 'LBL_SERVICE',
            'type' => 'enum',
            'options' => 'ppt-services-dom',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'product' => array(
            'name' => 'product',
            'vname' => 'LBL_PRODUCT',
            'type' => 'enum',
            'options' => 'ppt-products-dom',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'c_weight' => array(
            'name' => 'c_weight',
            'vname' => 'LBL_C_WEIGHT',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'rate' => array(
            'name' => 'rate',
            'vname' => 'LBL_RATE',
            'type' => 'float',
            'dbType' => 'float',
            'len' => '4',
            'precision' => '2',
            'massupdate' => 0,
            'required' => false,
            'reportable' => true,
        ),
        'issue' => array(
            'name' => 'issue',
            'vname' => 'LBL_ISSUE',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),
        'valid_from' => array(
            'name' => 'valid_from',
            'vname' => 'LBL_VALID_FROM',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),
        'currency' => array(
            'name' => 'currency',
            'vname' => 'LBL_CURRENCY',
            'type' => 'varchar',
            'len' => 50,
            'size' => 20,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'nature_of_goods' => array(
            'name' => 'nature_of_goods',
            'vname' => 'LBL_NATURE_OF_GOODS',
            'type' => 'enum',
            'options' => 'ppt-nature-of-goods-dom',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),

        //flags
        'capri' => array(
            'name' => 'capri',
            'vname' => 'LBL_CAPRI',
            'type' => 'bool',
            'default' => 1,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'add_hoc' => array(
            'name' => 'add_hoc',
            'vname' => 'LBL_ADD_HOC',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'high_dense' => array(
            'name' => 'high_dense',
            'vname' => 'LBL_HIGH_DENSE',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'freight_material' => array(
            'name' => 'freight_material',
            'vname' => 'LBL_FREIGHT_MATERIAL',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'lost_business' => array(
            'name' => 'lost_business',
            'vname' => 'LBL_LOST_BUSINESS',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'fup' => array(
            'name' => 'fup',
            'vname' => 'LBL_FUP',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'proactive_call' => array(
            'name' => 'proactive_call',
            'vname' => 'LBL_PROACTIVE_CALL',
            'type' => 'bool',
            'default' => 0,
            'massupdate' => 0,
            'reportable' => true,
        ),

        //related
        'account_id' => array(
            'name' => 'account_id',
            'rname' => 'id',
            'id_name' => 'account_id',
            'type' => 'id',
            'dbType' => 'id',
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'isnull' => 'false',
            'vname' => 'LBL_ACCOUNT_ID',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'account_name' => array(
            'name' => 'account_name',
            'vname' => 'LBL_ACCOUNT',
            'type' => 'relate',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'rname' => 'name',
            'id_name' => 'account_id',
            'source' => 'non-db',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'shipper_id' => array(
            'name' => 'shipper_id',
            'rname' => 'id',
            'id_name' => 'shipper_id',
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'isnull' => 'false',
            'vname' => 'LBL_SHIPPER_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'shipper_name' => array(
            'name' => 'shipper_name',
            'vname' => 'LBL_SHIPPER',
            'type' => 'relate',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'rname' => 'name',
            'source' => 'non-db',
            'id_name' => 'shipper_id',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'contact_id' => array(
            'name' => 'contact_id',
            'rname' => 'id',
            'id_name' => 'contact_id',
            'table' => 'ppt_contacts',
            'module' => 'PPT_Contacts',
            'isnull' => 'false',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'contact_name' => array(
            'name' => 'contact_name',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'len' => 255,
            'massupdate' => 0,
            'rname' => 'name',
            'source' => 'non-db',
            'id_name' => 'contact_id',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_contacts',
            'module' => 'PPT_Contacts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'ppt_accounts' => array(
            'name' => 'ppt_accounts',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contract_accounts',
            'source' => 'non-db',
            'module' => 'PPT_Accounts',
            'bean_name' => 'PPT_Account',
        ),

        'ppt_shippers' => array(
            'name' => 'ppt_shippers',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contract_shippers',
            'source' => 'non-db',
            'module' => 'PPT_Accounts',
            'bean_name' => 'PPT_Account',
        ),

        'ppt_contacts' => array(
            'name' => 'ppt_contacts',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contact_contracts',
            'source' => 'non-db',
            'module' => 'PPT_Contacts',
            'bean_name' => 'PPT_Contact',
        ),

    ),
    'indices' => array(
        array(
            'name' => 'idx_account',
            'type' => 'index',
            'fields' => array('account_id'),
        ),
        array(
            'name' => 'idx_shipper',
            'type' => 'index',
            'fields' => array('shipper_id'),
        ),
        array(
            'name' => 'idx_origin',
            'type' => 'index',
            'fields' => array('origin'),
        ),
        array(
            'name' => 'idx_dest',
            'type' => 'index',
            'fields' => array('dest'),
        ),
        array(
            'name' => 'idx_contact',
            'type' => 'index',
            'fields' => array('contact_id'),
        ),
    ),
    'relationships' => array(
        'spq_accounts' => array(
            'lhs_module' => 'PPT_Accounts',
            'lhs_table' => 'ppt_accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'PPT_Contracts',
            'rhs_table' => 'ppt_contracts',
            'rhs_key' => 'account_id',
            'relationship_type' => 'one-to-many',
        ),
        'spq_shippers' => array(
            'lhs_module' => 'PPT_Accounts',
            'lhs_table' => 'ppt_accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'PPT_Contracts',
            'rhs_table' => 'ppt_contracts',
            'rhs_key' => 'shipper_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}

VardefManager::createVardef('PPT_SPQ', 'PPT_SPQ', array('basic', 'assignable', 'security_group', 'acl'));