<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['PPT_Account'] = array(
    'table' => 'ppt_accounts',
    'audited' => false,
    'inline_edit' => true,
    'duplicate_merge' => 'disabled',
    'fields' => array(
        'active_flag' =>
            array(
                'required' => false,
                'name' => 'active_flag',
                'vname' => 'LBL_ACTIVE_FLAG',
                'type' => 'bool',
                'massupdate' => 0,
                'default' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'importonly_flag' =>
            array(
                'required' => false,
                'name' => 'importonly_flag',
                'vname' => 'LBL_IMPORTONLY_FLAG',
                'type' => 'bool',
                'massupdate' => 0,
                'default' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'localhero_flag' =>
            array(
                'required' => false,
                'name' => 'localhero_flag',
                'vname' => 'LBL_LOCALHERO_FLAG',
                'type' => 'bool',
                'massupdate' => 0,
                'default' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'cdb_num' =>
            array(
                'required' => false,
                'name' => 'cdb_num',
                'vname' => 'LBL_CDB_NUM',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => 100000000,
                'max' => false,
                'validation' =>
                    array(
                        'type' => 'range',
                        'min' => 100000000,
                        'max' => false,
                    ),
            ),
        'sales_level_6' =>
            array(
                'required' => true,
                'name' => 'sales_level_6',
                'vname' => 'LBL_SALES_LEVEL_6',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'ppt-sales-level-6-dom',
                'studio' => 'visible',
                'dbType' => 'enum',
            ),
        'company_type' =>
            array(
                'required' => true,
                'name' => 'company_type',
                'vname' => 'LBL_COMPANY_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'ppt-company-types-dom',
                'studio' => 'visible',
                'dbType' => 'enum',
            ),
        'station' =>
            array(
                'required' => true,
                'name' => 'station',
                'vname' => 'LBL_STATION',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'ppt-stations-dom',
                'studio' => 'visible',
                'dbType' => 'enum',
            ),
        'industry_type' =>
            array(
                'required' => true,
                'name' => 'industry_type',
                'vname' => 'LBL_INDUSTRY_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'required',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'ppt-industries-dom',
                'studio' => 'visible',
                'dbType' => 'enum',
            ),
        'acc_short_name' =>
            array(
                'required' => false,
                'name' => 'acc_short_name',
                'vname' => 'LBL_ACC_SHORT_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'bkng_short_name' =>
            array(
                'required' => false,
                'name' => 'bkng_short_name',
                'vname' => 'LBL_BKNG_SHORT_NAME',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'iata_num' =>
            array(
                'required' => false,
                'name' => 'iata_num',
                'vname' => 'LBL_IATA_NUM',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
        'cass_num' =>
            array(
                'required' => false,
                'name' => 'cass_num',
                'vname' => 'LBL_CASS_NUM',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
        'sap_num' =>
            array(
                'required' => false,
                'name' => 'sap_num',
                'vname' => 'LBL_SAP_NUM',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
        'phone' =>
            array(
                'required' => false,
                'name' => 'phone',
                'vname' => 'LBL_PHONE',
                'type' => 'phone',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'dbType' => 'varchar',
            ),
        'fax' =>
            array(
                'required' => false,
                'name' => 'fax',
                'vname' => 'LBL_FAX',
                'type' => 'phone',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
                'dbType' => 'varchar',
            ),
        'email' =>
            array(
                'required' => false,
                'name' => 'email',
                'vname' => 'LBL_EMAIL',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'website' =>
            array(
                'required' => false,
                'name' => 'website',
                'vname' => 'LBL_WEBSITE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'address_type' =>
            array(
                'required' => false,
                'name' => 'address_type',
                'vname' => 'LBL_ADDRESS_TYPE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '100',
                'size' => '20',
            ),
        'address_street' =>
            array(
                'required' => false,
                'name' => 'address_street',
                'vname' => 'LBL_ADDRESS_STREET',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '150',
                'size' => '20',
            ),
        'address_lane' =>
            array(
                'required' => false,
                'name' => 'address_lane',
                'vname' => 'LBL_ADDRESS_LANE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '50',
                'size' => '20',
            ),
        'address_building' =>
            array(
                'required' => false,
                'name' => 'address_building',
                'vname' => 'LBL_ADDRESS_BUILDING',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '50',
                'size' => '20',
            ),
        'address_area' =>
            array(
                'required' => false,
                'name' => 'address_area',
                'vname' => 'LBL_ADDRESS_AREA',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '150',
                'size' => '20',
            ),
        'address_po_box' => array(
            'required' => false,
            'name' => 'address_po_box',
            'vname' => 'LBL_ADDRESS_PO_BOX',
            'type' => 'varchar',
            'massupdate' => 0,
            'importable' => true,
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'merge_filter' => 'disabled',
            'len' => '50',
            'size' => '20',
        ),
        'address_zip' =>
            array(
                'required' => false,
                'name' => 'address_zip',
                'vname' => 'LBL_ADDRESS_ZIP',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '50',
                'size' => '20',
            ),
        'address_city' =>
            array(
                'required' => false,
                'name' => 'address_city',
                'vname' => 'LBL_ADDRESS_CITY',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '100',
                'size' => '20',
            ),
        'address_state' =>
            array(
                'required' => false,
                'name' => 'address_state',
                'vname' => 'LBL_ADDRESS_STATE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '100',
                'size' => '20',
            ),
        'address_country' =>
            array(
                'required' => false,
                'name' => 'address_country',
                'vname' => 'LBL_ADDRESS_COUNTRY',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'lavlsv_num' =>
            array(
                'required' => false,
                'name' => 'lavlsv_num',
                'vname' => 'LBL_LAVLSV_NUM',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'inline_edit' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'account_role' => array(
            'required' => false,
            'name' => 'account_role',
            'vname' => 'LBL_ACCOUNT_ROLE',
            'type' => 'enum',
            'dbType' => 'enum',
            'len' => '100',
            'size' => '20',
            'options' => 'ppt-account-roles-dom',
            'massupdate' => 0,
            'importable' => true,
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'merge_filter' => 'disabled',
        ),

        //relations
        'ppt_contacts' => array(
            'name' => 'ppt_contacts',
            'type' => 'link',
            'relationship' => 'account_contacts',
            'module' => 'PPT_Contacts',
            'bean_name' => 'PPT_Contact',
            'source' => 'non-db',
        ),
        'ppt_contracts' => array(
            'name' => 'ppt_contracts',
            'type' => 'link',
            'relationship' => 'contract_accounts',
            'module' => 'PPT_Contracts',
            'bean_name' => 'PPT_Contract',
            'source' => 'non-db',
        ),

    ),
    'indices' => array(
        array(
            'name' => 'idx_name',
            'type' => 'index',
            'fields' => array('name'),
        ),
        array(
            'name' => 'idx_cdb_num',
            'type' => 'index',
            'fields' => array('cdb_num'),
        ),
        array(
            'name' => 'idx_lavlsv_num',
            'type' => 'index',
            'fields' => array('lavlsv_num'),
        ),
    ),
    'relationships' => array(
       ////        strtolower($module)."_spq" => array(
////            'lhs_module' => $module,
////            'lhs_table' => $table_name,
////            'lhs_key' => 'id',
////            'rhs_module' => 'myppt_SPQ',
////            'rhs_table' => 'myppt_spq',
////            'rhs_key' => 'agent_id',
////            'relationship_type' => 'one-to-many',
////        ),
////        strtolower($module)."_pa" => array(
////            'lhs_module' => $module,
////            'lhs_table' => $table_name,
////            'lhs_key' => 'id',
////            'rhs_module' => 'myppt_PA',
////            'rhs_table' => 'myppt_pa',
////            'rhs_key' => 'agent_id',
////            'relationship_type' => 'one-to-many',
////        ),
        'account_contacts' => array(
            'lhs_module' => 'PPT_Accounts',
            'lhs_table' => 'ppt_accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'PPT_Contacts',
            'rhs_table' => 'ppt_contacts',
            'rhs_key' => 'account_id',
            'relationship_type' => 'one-to-many',
        ),
////        strtolower($module)."_contracts" => array(
////            'lhs_module' => $module,
////            'lhs_table' => $table_name,
////            'lhs_key' => 'id',
////            'rhs_module' => 'myppt_Contracts',
////            'rhs_table' => 'myppt_contracts',
////            'rhs_key' => 'account_id',
////            'relationship_type' => 'one-to-many',
////        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('PPT_Accounts', 'PPT_Account', array('basic', 'assignable', 'security_groups'));