<?php

$dictionary['PPT_Contract'] = array(
    'table' => 'ppt_contracts',
    'audited' => false,
    'inline_edit' => true,
    'duplicate_merge' => 'disabled',
    'fields' => array(
        'number' => array(
            'name' => 'number',
            'vname' => 'LBL_NUMBER',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'origin' => array(
            'name' => 'origin',
            'vname' => 'LBL_ORIGIN',
            'type' => 'enum',
            'options' => 'ppt-airports-dom',
            'len' => 50,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'dest' => array(
            'name' => 'dest',
            'vname' => 'LBL_DEST',
            'type' => 'enum',
            'options' => 'ppt-airports-dom',
            'len' => 50,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'service' => array(
            'name' => 'service',
            'vname' => 'LBL_SERVICE',
            'type' => 'enum',
            'options' => 'ppt-services-dom',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),
        'product' => array(
            'name' => 'product',
            'vname' => 'LBL_PRODUCT',
            'type' => 'enum',
            'options' => 'ppt-products-dom',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
        ),

        'shipping_date' => array(
            'name' => 'shipping_date',
            'vname' => 'LBL_SHIPPING_DATE',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),
        'arrival_date' => array(
            'name' => 'arrival_date',
            'vname' => 'LBL_ARRIVAL_DATE',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => '+3 day',
        ),
        'scc' => array(
            'name' => 'scc',
            'vname' => 'LBL_SCC',
            'type' => 'enum',
            'dbType' => 'enum',
            'options' => 'ppt-commodity-types-dom',
            'massupdate' => 0,
            'reportable' => true,
            'len' => 50,
        ),
        'iata_code' => array(
            'name' => 'iata_code',
            'vname' => 'LBL_IATA_CODE',
            'type' => 'varchar',
            'massupdate' => 0,
            'required' => false,
            'reportable' => true,
            'len' => 100,
        ),
        'status' => array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Not Started',
            'importable' => 'true',
            'reportable' => true,
            'len' => 100,
            'size' => '20',
            'options' => 'contract_status_list',
            'studio' => 'visible',
        ),
        'start_date' => array(
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),
        'end_date' => array(
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => '+3 day',
        ),
        'customer_signed_date' => array(
            'name' => 'customer_signed_date',
            'vname' => 'LBL_CUSTOMER_SIGNED_DATE',
            'type' => 'date',
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),
        'company_signed_date' => array(
            'name' => 'company_signed_date',
            'vname' => 'LBL_COMPANY_SIGNED_DATE',
            'type' => 'date',
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
            'display_default' => 'now',
        ),

        //flights
        'flight_date' => array(
            'name' => 'flight_date',
            'vname' => 'LBL_FLIGHT_DATE',
            'type' => 'date',
            'required' => false,
            'massupdate' => 0,
            'reportable' => true,
            'source' => 'non-db',
            'display_default' => 'now',
        ),

        'flight' => array(
            'name' => 'flight',
            'vname' => 'LBL_FLIGHT',
            'type' => 'text',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'rows' => 10,
            'cols' => 100,
        ),

        'line_items' => array(
            'name' => 'line_items',
            'vname' => 'LBL_LINE_ITEMS',
            'type' => 'text',
            'required' => true,
            'massupdate' => 0,
            'reportable' => true,
            'rows' => 10,
            'cols' => 100,
        ),

        //relations
        'account_id' => array(
            'name' => 'account_id',
            'rname' => 'id',
            'id_name' => 'account_id',
            'type' => 'id',
            'dbType' => 'id',
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'isnull' => 'false',
            'vname' => 'LBL_ACCOUNT_ID',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'account_name' => array(
            'name' => 'account_name',
            'vname' => 'LBL_ACCOUNT',
            'type' => 'relate',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'rname' => 'name',
            'id_name' => 'account_id',
            'source' => 'non-db',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'shipper_id' => array(
            'name' => 'shipper_id',
            'rname' => 'id',
            'id_name' => 'shipper_id',
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'isnull' => 'false',
            'vname' => 'LBL_SHIPPER_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'shipper_name' => array(
            'name' => 'shipper_name',
            'vname' => 'LBL_SHIPPER',
            'type' => 'relate',
            'len' => 255,
            'required' => true,
            'massupdate' => 0,
            'rname' => 'name',
            'source' => 'non-db',
            'id_name' => 'shipper_id',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_accounts',
            'module' => 'PPT_Accounts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'contact_id' => array(
            'name' => 'contact_id',
            'rname' => 'id',
            'id_name' => 'contact_id',
            'table' => 'ppt_contacts',
            'module' => 'PPT_Contacts',
            'isnull' => 'false',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'contact_name' => array(
            'name' => 'contact_name',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'len' => 255,
            'massupdate' => 0,
            'rname' => 'name',
            'source' => 'non-db',
            'id_name' => 'contact_id',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'table' => 'ppt_contacts',
            'module' => 'PPT_Contacts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'ppt_accounts' => array(
            'name' => 'ppt_accounts',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contract_accounts',
            'source' => 'non-db',
            'module' => 'PPT_Accounts',
            'bean_name' => 'PPT_Account',
        ),

        'ppt_shippers' => array(
            'name' => 'ppt_shippers',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contract_shippers',
            'source' => 'non-db',
            'module' => 'PPT_Accounts',
            'bean_name' => 'PPT_Account',
        ),

        'ppt_contacts' => array(
            'name' => 'ppt_contacts',
            'type' => 'link',
            'link_type' => 'one',
            'relationship' => 'contact_contracts',
            'source' => 'non-db',
            'module' => 'PPT_Contacts',
            'bean_name' => 'PPT_Contact',
        ),

    ),
    'indices' => array(
        array(
            'name' => 'idx_account',
            'type' => 'index',
            'fields' => array('account_id'),
        ),
        array(
            'name' => 'idx_shipper',
            'type' => 'index',
            'fields' => array('shipper_id'),
        ),
        array(
            'name' => 'idx_origin',
            'type' => 'index',
            'fields' => array('origin'),
        ),
        array(
            'name' => 'idx_dest',
            'type' => 'index',
            'fields' => array('dest'),
        ),
        array(
            'name' => 'idx_contact',
            'type' => 'index',
            'fields' => array('contact_id'),
        ),
    ),
    'relationships' => array(
        'contract_accounts' => array(
            'lhs_module' => 'PPT_Accounts',
            'lhs_table' => 'ppt_accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'PPT_Contracts',
            'rhs_table' => 'ppt_contracts',
            'rhs_key' => 'account_id',
            'relationship_type' => 'one-to-many',
        ),
        'contract_shippers' => array(
            'lhs_module' => 'PPT_Accounts',
            'lhs_table' => 'ppt_accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'PPT_Contracts',
            'rhs_table' => 'ppt_contracts',
            'rhs_key' => 'shipper_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('PPT_Contracts', 'PPT_Contract', array('basic', 'assignable', 'security_groups',));